version: 2
jobs:
  test:
    working_directory: /go/src/github.com/pottava/basicauth-reverseproxy
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/...
      - run: dep ensure
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12.5
      - run:
          name: Run tests
          command: |
            ./bin/golangci-lint run --config .golangci.yml
            go test -cover -bench -benchmem $(go list ./...)
  build:
    working_directory: /go/src/github.com/pottava/basicauth-reverseproxy
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/...
      - run: dep ensure
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Build and release
          command: |
            mkdir artifacts
            gox --osarch "linux/amd64 darwin/amd64 windows/amd64" -ldflags "-s -w -X main.date=$(date +%Y-%m-%d --utc) -X main.version=${CIRCLE_TAG}" -output "./artifacts/{{.OS}}_{{.Arch}}"
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  dev:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
