app:
  build: .
  command: go run /go/src/github.com/pottava/basicauth-reverseproxy/main.go
  ports:
    - 8080:80
  volumes:
    - .:/go/src/github.com/pottava/basicauth-reverseproxy
  environment:
    - PROXY_URL
    - BASIC_AUTH_USER
    - BASIC_AUTH_PASS
    - SSL_CERT_PATH
    - SSL_KEY_PATH
  container_name: app
