version: "2"

services:
  app:
    build: dev/
    image: basicauth-reverseproxy:dev
    command: go run /go/src/github.com/pottava/basicauth-reverseproxy/main.go
    ports:
      - 8080:80
    volumes:
      - .:/go/src/github.com/pottava/basicauth-reverseproxy
    environment:
      - PROXY_PATTERNS="/app/envs=http://aa:8080/,localhost=http://bb:8080/,*=http://cc:8080/"
      # - PROXY_URL=http:/cc/
      - BASIC_AUTH_USER
      - BASIC_AUTH_PASS
      - SSL_CERT_PATH
      - SSL_KEY_PATH
      - ACCESS_LOG=true
      - CONTENT_ENCODING
      - HEALTHCHECK_PATH
    container_name: app

  a:
    image: pottava/http-re:1.2
    environment:
      - NAME=aa
    container_name: aa

  b:
    image: pottava/http-re:1.2
    environment:
      - NAME=bb
    container_name: bb

  c:
    image: pottava/http-re:1.2
    environment:
      - NAME=cc
    container_name: cc
