version: "2"

services:
  app:
    build: dev/
    image: basicauth-reverseproxy:dev
    command: go run /go/src/github.com/pottava/basicauth-reverseproxy/main.go
    ports:
      - 80:80
    volumes:
      - .:/go/src/github.com/pottava/basicauth-reverseproxy
    environment:
      - PROXY_PATTERNS="/.well-known/=http://aa/,localhost=http://bb/,*=http://cc/"
      # - PROXY_URL=http:/cc/
      - BASIC_AUTH_USER
      - BASIC_AUTH_PASS
      - SSL_CERT_PATH
      - SSL_KEY_PATH
      - ACCESS_LOG=true
      - CONTENT_ENCODING
    container_name: app

  a:
    image: dockercloud/hello-world
    environment:
      - NAME=aa
    container_name: aa

  b:
    image: dockercloud/hello-world
    environment:
      - NAME=bb
    container_name: bb

  c:
    image: dockercloud/hello-world
    environment:
      - NAME=cc
    container_name: cc
