FROM mcr.microsoft.com/windows/nanoserver:10.0.14393.2485

ENV APP_PORT=80 \
    ACCESS_LOG=false \
    CONTENT_ENCODING=true

ADD https://github.com/pottava/basicauth-reverseproxy/releases/download/v1.1.2/basicauth-reverseproxy_windows_amd64.exe basicauth-reverseproxy.exe
ENTRYPOINT ["C:\\basicauth-reverseproxy.exe"]
